### ISSUE TITLE
No verification mails sent on create new account

### ISSUE THREAD

**Issue by EskeRahn** [mypaint/mypaint.github.io#31]
No verification mails sent on create new account.

I tried to create two different accounts on two different mail domains, I receive no verification mail - and yes I have checked spam filters and folders.

EDIT: Moved the question replicated here to a new thread
https://community.mypaint.org/t/x/574

**Comment by achadwick** [comment]
@EskeRahn
(The report you're wanting to write sounds a lot like a GTK issue. Hopefully the next release will use GTK 3.22.5 which has some wintab stability fixes, but having learned how that subsystem works (it's a mess!) I can quite see this fault not being fixed by our using that. 

The GTK bug tracker is here: [sample search for "wintab"](https://bugzilla.gnome.org/buglist.cgi?bug_status=__all__&content=wintab&no_redirect=1&order=Importance&product=gtk%2B&query_format=specific), [bug report form (needs a login)](https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B).

If you can install MSYS2 and reproduce your issue with the drawing area tester in gtk3-demo, that will help the GTK+ folks a lot.)

Anyway, enough side issue ☺

**Comment by odysseywestra** [comment]
I'm getting a domain not found error on our Mailgun Account. Sadly, Mailgun
trips over those types of domains. You'll probably have to use a different
mail account that has different domain name.

What I can do is delete those two accounts you tried to create and sign up
with a different email address.

**Comment by EskeRahn** [comment]
@odysseywestra
Odd Yes please delete them (Or activate one manually, you can send an ordinary mail I can reply to if you need to). Is it the entire .dk top level domain it dislikes, or just the two used? (they are completely unrelated, not hosted at the same servers or anything)

@achadwick 
(Yes wrong thread. I would be glad to help, but do not know what I need to fetch to do so)

**Comment by EskeRahn** [comment]
@achadwick 
(Just tried to install "Pinta 1.6" and "Inkscape 0.91" that is supposedly both also GTK+ based, and they do NOT have the same issue, so does not sound like the issue is in the GTK+)
it is 0345 here, so no more testing the next couple of hours.... ;)

**Comment by odysseywestra** [comment]
Here is the error message from the Mailgun log:
```
Will retry in 7200 seconds: noreply@community.mypaint.org → junk@eskerahn.dk
'[MyPaint Community] Confirm your new account' Server response: 450 450
4.1.8 <bounce+4d451e.4468817-junk=eskerahn.dk@no-reply.mypaint.org>: Sender
address rejected: Domain not found
```

I've deleted both accounts. You could try to sign up with Github, but if
it's still using the same domains, then that may pose a problem. If you
can't use a different mail provider, I'll manually activate the account.
Just realize that you will get no notifications or important messages from
the site.

**Comment by EskeRahn** [comment]
@odysseywestra
I used the github account as you suggested, to the same mail. Please remove my mail-address details from the above post...

**Comment by odysseywestra** [comment]
Okay about the email. Looks good on my end. I'll consider this resolved then.

**Comment by EskeRahn** [comment]
I guess the problem is still there - though it does not matter to me.

**Comment by odysseywestra** [comment]
Did you get an activation email when you used the Github SSO to sign up?

**Comment by EskeRahn** [comment]
Yes I got a confirmation mail from GitHub to one of the mails.

See below, (with bits XXXX'ed out).


Hi @EskeRahn!

Help us secure your GitHub account by verifying your email address (XXXXXX@sol.dk). This lets you access all of GitHub's features.
Verify email address

Button not working? Paste the following link into your browser:
https://github.com/users/EskeRahn/emails/XXXXXXXXX/confirm_verification/XXXXXXXXXX

You’re receiving this email because you recently created a new GitHub account or added a new email address. If this wasn’t you, please ignore this email.

**Comment by EskeRahn** [comment]
Ah. I found something at the Spamtitan-server. You claim to send from a non existing domain (partly XXXX'ed out):

"
**Unknown Sender Domain**
bounce+4d451XXXXXXXXXXXX.dk@no-reply.mypaint.org
"

**Comment by achadwick** [comment]
@odysseywestra Let me know if any DNS records need adding.

**Comment by odysseywestra** [comment]
I did a test on a site someone the Discourse Community forms Suggested.
https://www.mail-tester.com/web-3qv54&reloaded=1

By the looks of it, We still need to set MX records and we are blocked by one SPAM Filter List site. So that my also be part of the problem. @achadwick , if you could update the MX records to these settings, that would be a start. Then I send a test email to @EskeRahn to see if it still a problem.
 ![screenshot from 2017-01-05 18-49-31](https://cloud.githubusercontent.com/assets/1840562/21705938/08bdc5c2-d378-11e6-8487-7fe43c23d4c6.png)

**Comment by achadwick** [comment]
@odysseywestra Thanks for doing the detective work!

I've added MX records as above for no-reply.mypaint.org. Can you give it a few minutes and then test?

**Comment by EskeRahn** [comment]
@achadwick 
Just tested, it works :)
