### ISSUE TITLE
github pages; DNS ip address updates needed

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint.github.io#39]
I published a github page and received an email:

The page build completed successfully, but returned the following warning for the `master` branch:

The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/en/articles/using-a-custom-domain-with-github-pages.

The correct IPs appear to be:

    185.199.108.153
    185.199.109.153 
    185.199.110.153
    185.199.111.153

I'm pretty sure @jonnor has control of the domain, which is also expiring early next year.  Not sure what the long-term plan for that is :-)

**Comment by odysseywestra** [comment]
Triage Note: Transferred issue to website repository.

**Comment by jtojnar** [comment]
This is required for #40

**Comment by odysseywestra** [comment]
@jonnor  you still have the access to the domain rights for the `mypaint.org`? If so, we would like to transfer the domain to an account controlled by the mypaint community. 

We're going to first try it with the `mypaint.app` since that domain requires https so its a good testing ground. Once that sorted out, then we can proceed with moving the .org domain if you are okay with that.

**Comment by jonnor** [comment]
@odysseywestra yes, I just renewed the domain for another year. Happy to transfer it to an account for that current MyPaint maintainers control. Preferably one with some level of shared access for multiple people, so that one avoids having a bus factor of 1.

**Comment by odysseywestra** [comment]
@jonnor  I think, I'm ready to at least transfer the domain to a new nameserver. I've been working on moving any dns record I could find that is related to mypaint.org over to a linode nameserver. With that said, I think the correct course of action is to add the Nameserver on top of the mythic beast nameservers so that if anything breaks it just a matter of deleting the the linode nameserver. 

Long term, I plan on moving the community forums over to a new VPS on Linode and hosting the website on the object storage it has. This would also allow me or someone else to run custom ci tools or self-host mypaint git repo if we need to. I can even add you as a user on that linode account so you can edit the DNS records too.  I might let go of the mypaint.app domain

Here are the NS listed for Linode:
ns1.linode.com

They can to up to ns5.linode.com

**Comment by odysseywestra** [comment]
Closing in favor of #41 too keep thing consistent issues wise.
