### ISSUE TITLE
Website --> HTTPS

### ISSUE THREAD

**Issue by Echolon** [mypaint/mypaint.github.io#40]
Hello,

your website would be more attractive (and secure) if it would be HTTPS encrypted.

https://letsencrypt.org/

Cheers

**Comment by jtojnar** [comment]
Since you are using `A` record, you will need to update the DNS record to the new IP address and then enable HTTPS enforcement as described in:

* https://github.blog/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain
* https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by odysseywestra** [comment]
As of right now the nameservers are in limbo so that what been preventing us from making any changes. Since the website is served by github pages, it isn't a 911 situation, and if by chance the nameservers drop we can switch to the github.io domain temporally till we can get the new nameserver back up. I have a backup domain setup that I can hotswitch for the Fourms atm too.

After 2.0 is release, I'm going todo a complete review of all our CI tools and that when I'll begin to resolve the nameserver issue.

**Comment by odysseywestra** [comment]
Moved website to https://mypaint.app to at least address this issue. The DNS part of mypaint.org is still in limbo, but I am working on resolving that in #39
